# Generated by Django 4.0.4 on 2022-04-18 21:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('balance', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'table_users',
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=30, unique=True)),
                ('transaction_type', models.CharField(max_length=6)),
                ('transaction_date', models.DateField(default=datetime.date.today)),
                ('transaction_status', models.CharField(max_length=6)),
                ('transaction_amount', models.FloatField(default=0)),
                ('reason', models.CharField(max_length=100)),
                ('transaction_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_from', to=settings.AUTH_USER_MODEL)),
                ('transaction_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_with', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
